name: generate_pdf_invoice_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.1.3
  intl: ^0.17.0
  logger: ^1.0.0
  
  open_file: ^3.2.1
  path_provider: ^2.0.1
  pdf: ^3.1.0
  rive: ^0.7.30
  google_mobile_ads: ^1.3.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  syncfusion_flutter_pdf: ^19.4.40-beta
  jiffy: ^5.0.0



dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
